name: artifacts workflow
on: workflow_dispatch
jobs:
  WRITE_ARTIFACTS:
    runs-on: ubuntu-latest
    steps:
      - name: Write artifact file
        run: echo "This is a dummy artifact file" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-artifact
          path: artifact.txt

      - name: Upload artifact
        uses: actions/download-artifact@v4
        with:
          name: dummy-artifact

