name: Github secret

on: workflow_dispatch

jobs:
  ECHO_SECRET:
    runs-on: ubuntu-latest
    steps: 
      - name: ECHO_SECRET_WITHOUT_ENV
        run: echo "SECRET=${{ secrets.KEY}}"
      
      - name: ECHO_SECRET_WITH_ENV
        env: 
          KEY: ${{ secrets.KEY}}
        run: echo "${{ env.KEY}}"
      - run: echo "$KEY"