name: Basic Workflow

on:
  push:
    branches: ["main"]

env:
  GLOBAL_ENV: "Global Environment Variable"

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      LOCAL_ENV: "Local Environment Variable"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "$GLOBAL_ENV"

      - name: Run a multi-line script
        run: echo "${{env.GLOBAL_ENV}}"

      - name: Run a multi-line script
        run: echo "${{env.LOCAL_ENV}}"
  
  build-api:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "$LOCAL_ENV"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"
  
  package:
    needs: [build-app, build-db]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Ubuntu"

    
    
